apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-chart.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
type: Opaque
data:
  API_KEY: {{ .Values.secret.apiKey | b64enc | quote }}
